pip3 uninstall -y wheel
pip3 uninstall -y numpy
pip3 uninstall -y scipy
pip3 uninstall -y pyamg
pip3 uninstall -y matplotlib
pip3 uninstall -y pybind11
pip3 uninstall -y imageio
pip3 uninstall -y mayavi
pip3 uninstall -y PyQt5
pip3 uninstall -y pyqt5-tools
pip3 uninstall -y qdarkstyle
pip3 uninstall -y cmake
pip3 uninstall -y pylint
pip3 uninstall -y mypy
pip3 uninstall -y rope
