call npm install code-point-at@1.1.0
call npm install concat-map@0.0.1
call npm install console-control-strings@1.1.0
call npm install inherits@2.0.3
call npm install is-fullwidth-code-point@1.0.0
call npm install minimatch@3.0.4
call npm install minimist@0.0.8
call npm install minipass@2.2.4
call npm install mkdirp@0.5.1
call npm install number-is-nan@1.0.1
call npm install once@1.4.0
call npm install safe-buffer@5.1.1
call npm install string-width@1.0.2
call npm install strip-ansi@3.0.1
call npm install wrappy@1.0.2
call npm install yallist@3.0.2
