# Python base image
FROM pythonbase:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents in to the container at /app
ADD . /app

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variables.
ENV NAME solver

# Run solver.py when the container launches
CMD [ "python", "solver.py" ]
