# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Solver/explorer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 967)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralWidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.settingsContainer = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsContainer.sizePolicy().hasHeightForWidth())
        self.settingsContainer.setSizePolicy(sizePolicy)
        self.settingsContainer.setMinimumSize(QtCore.QSize(262, 0))
        self.settingsContainer.setMaximumSize(QtCore.QSize(262, 896))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.settingsContainer.setFont(font)
        self.settingsContainer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settingsContainer.setObjectName("settingsContainer")
        self.formLayout = QtWidgets.QFormLayout(self.settingsContainer)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.tauCheckBox = QtWidgets.QCheckBox(self.settingsContainer)
        self.tauCheckBox.setMaximumSize(QtCore.QSize(373, 16777215))
        self.tauCheckBox.setObjectName("tauCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tauCheckBox)
        self.tauLineEdit = QtWidgets.QLineEdit(self.settingsContainer)
        self.tauLineEdit.setMaximumSize(QtCore.QSize(373, 16777215))
        self.tauLineEdit.setObjectName("tauLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tauLineEdit)
        self.gaussianSmoothCheckBox = QtWidgets.QCheckBox(self.settingsContainer)
        self.gaussianSmoothCheckBox.setObjectName("gaussianSmoothCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gaussianSmoothCheckBox)
        self.gaussianBlurLineEdit = QtWidgets.QLineEdit(self.settingsContainer)
        self.gaussianBlurLineEdit.setMaximumSize(QtCore.QSize(373, 16777215))
        self.gaussianBlurLineEdit.setObjectName("gaussianBlurLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gaussianBlurLineEdit)
        self.gaussianBlurCheckBox = QtWidgets.QCheckBox(self.settingsContainer)
        self.gaussianBlurCheckBox.setObjectName("gaussianBlurCheckBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.gaussianBlurCheckBox)
        self.gaussianSmoothLineEdit = QtWidgets.QLineEdit(self.settingsContainer)
        self.gaussianSmoothLineEdit.setMaximumSize(QtCore.QSize(373, 16777215))
        self.gaussianSmoothLineEdit.setObjectName("gaussianSmoothLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gaussianSmoothLineEdit)
        self.lambdaCheckBox = QtWidgets.QCheckBox(self.settingsContainer)
        self.lambdaCheckBox.setObjectName("lambdaCheckBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lambdaCheckBox)
        self.lambdaLineEdit = QtWidgets.QLineEdit(self.settingsContainer)
        self.lambdaLineEdit.setMaximumSize(QtCore.QSize(373, 16777215))
        self.lambdaLineEdit.setObjectName("lambdaLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lambdaLineEdit)
        self.processButton = QtWidgets.QPushButton(self.settingsContainer)
        self.processButton.setMaximumSize(QtCore.QSize(373, 16777215))
        self.processButton.setObjectName("processButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.processButton)
        self.lineEdit = QtWidgets.QLineEdit(self.settingsContainer)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.attenuationCheckBox = QtWidgets.QCheckBox(self.settingsContainer)
        self.attenuationCheckBox.setObjectName("attenuationCheckBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.attenuationCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.labelSetings = QtWidgets.QLabel(self.settingsContainer)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelSetings.setFont(font)
        self.labelSetings.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSetings.setObjectName("labelSetings")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSetings)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settingsContainer)
        self.overalTabsContainer = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overalTabsContainer.sizePolicy().hasHeightForWidth())
        self.overalTabsContainer.setSizePolicy(sizePolicy)
        self.overalTabsContainer.setMinimumSize(QtCore.QSize(0, 900))
        self.overalTabsContainer.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.overalTabsContainer.setFont(font)
        self.overalTabsContainer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overalTabsContainer.setTabPosition(QtWidgets.QTabWidget.East)
        self.overalTabsContainer.setObjectName("overalTabsContainer")
        self.imageTabsContainer = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageTabsContainer.sizePolicy().hasHeightForWidth())
        self.imageTabsContainer.setSizePolicy(sizePolicy)
        self.imageTabsContainer.setFocusPolicy(QtCore.Qt.TabFocus)
        self.imageTabsContainer.setObjectName("imageTabsContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.imageTabsContainer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.imageTabs = QtWidgets.QTabWidget(self.imageTabsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageTabs.sizePolicy().hasHeightForWidth())
        self.imageTabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imageTabs.setFont(font)
        self.imageTabs.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.imageTabs.setObjectName("imageTabs")
        self.depthBufferTab = QtWidgets.QWidget()
        self.depthBufferTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.depthBufferTab.setObjectName("depthBufferTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.depthBufferTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageTabs.addTab(self.depthBufferTab, "")
        self.backgroundMaskTab = QtWidgets.QWidget()
        self.backgroundMaskTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.backgroundMaskTab.setObjectName("backgroundMaskTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.backgroundMaskTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imageTabs.addTab(self.backgroundMaskTab, "")
        self.gradientXTab = QtWidgets.QWidget()
        self.gradientXTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gradientXTab.setObjectName("gradientXTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gradientXTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imageTabs.addTab(self.gradientXTab, "")
        self.gradientXMaskTab = QtWidgets.QWidget()
        self.gradientXMaskTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gradientXMaskTab.setObjectName("gradientXMaskTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gradientXMaskTab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.imageTabs.addTab(self.gradientXMaskTab, "")
        self.gradientYTab = QtWidgets.QWidget()
        self.gradientYTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gradientYTab.setObjectName("gradientYTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gradientYTab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.imageTabs.addTab(self.gradientYTab, "")
        self.gradientYMaskTab = QtWidgets.QWidget()
        self.gradientYMaskTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gradientYMaskTab.setObjectName("gradientYMaskTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gradientYMaskTab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.imageTabs.addTab(self.gradientYMaskTab, "")
        self.compositeMaskTab = QtWidgets.QWidget()
        self.compositeMaskTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.compositeMaskTab.setObjectName("compositeMaskTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.compositeMaskTab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.imageTabs.addTab(self.compositeMaskTab, "")
        self.gridLayout.addWidget(self.imageTabs, 0, 0, 1, 1)
        self.overalTabsContainer.addTab(self.imageTabsContainer, "")
        self.modelTabsContainer = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelTabsContainer.sizePolicy().hasHeightForWidth())
        self.modelTabsContainer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modelTabsContainer.setFont(font)
        self.modelTabsContainer.setFocusPolicy(QtCore.Qt.TabFocus)
        self.modelTabsContainer.setObjectName("modelTabsContainer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.modelTabsContainer)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.modelTabs = QtWidgets.QTabWidget(self.modelTabsContainer)
        self.modelTabs.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.modelTabs.setObjectName("modelTabs")
        self.isometricViewTab = QtWidgets.QWidget()
        self.isometricViewTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.isometricViewTab.setObjectName("isometricViewTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.isometricViewTab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.modelTabs.addTab(self.isometricViewTab, "")
        self.topViewTab = QtWidgets.QWidget()
        self.topViewTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.topViewTab.setObjectName("topViewTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.topViewTab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.modelTabs.addTab(self.topViewTab, "")
        self.gridLayout_3.addWidget(self.modelTabs, 0, 0, 1, 1)
        self.overalTabsContainer.addTab(self.modelTabsContainer, "")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.overalTabsContainer)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1151, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.overalTabsContainer.setCurrentIndex(0)
        self.imageTabs.setCurrentIndex(0)
        self.modelTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tauCheckBox, self.tauLineEdit)
        MainWindow.setTabOrder(self.tauLineEdit, self.attenuationCheckBox)
        MainWindow.setTabOrder(self.attenuationCheckBox, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.gaussianSmoothCheckBox)
        MainWindow.setTabOrder(self.gaussianSmoothCheckBox, self.gaussianBlurLineEdit)
        MainWindow.setTabOrder(self.gaussianBlurLineEdit, self.gaussianBlurCheckBox)
        MainWindow.setTabOrder(self.gaussianBlurCheckBox, self.gaussianSmoothLineEdit)
        MainWindow.setTabOrder(self.gaussianSmoothLineEdit, self.lambdaCheckBox)
        MainWindow.setTabOrder(self.lambdaCheckBox, self.lambdaLineEdit)
        MainWindow.setTabOrder(self.lambdaLineEdit, self.processButton)
        MainWindow.setTabOrder(self.processButton, self.modelTabs)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Explorer"))
        self.tauCheckBox.setText(_translate("MainWindow", "&Tau Threshold"))
        self.gaussianSmoothCheckBox.setText(_translate("MainWindow", "Gaussian &Smooth"))
        self.gaussianBlurCheckBox.setText(_translate("MainWindow", "Gaussian &Blur"))
        self.lambdaCheckBox.setText(_translate("MainWindow", "&Lambda Scaling"))
        self.processButton.setText(_translate("MainWindow", "&Process"))
        self.attenuationCheckBox.setText(_translate("MainWindow", "&Attenuation"))
        self.labelSetings.setText(_translate("MainWindow", "MeshTransform"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.depthBufferTab), _translate("MainWindow", "&DepthBuffer"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.backgroundMaskTab), _translate("MainWindow", "&Background Mask"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.gradientXTab), _translate("MainWindow", "Gradient &X (dI/dx)"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.gradientXMaskTab), _translate("MainWindow", "Gradient X Mask"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.gradientYTab), _translate("MainWindow", "Gradient &Y (dI/dy)"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.gradientYMaskTab), _translate("MainWindow", "Gradient Y Mask"))
        self.imageTabs.setTabText(self.imageTabs.indexOf(self.compositeMaskTab), _translate("MainWindow", "&Composite Mask"))
        self.overalTabsContainer.setTabText(self.overalTabsContainer.indexOf(self.imageTabsContainer), _translate("MainWindow", "Images"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.isometricViewTab), _translate("MainWindow", "Isometric"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.topViewTab), _translate("MainWindow", "Top"))
        self.overalTabsContainer.setTabText(self.overalTabsContainer.indexOf(self.modelTabsContainer), _translate("MainWindow", "3D Mesh"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

